### ISSUE TITLE
Úkoly slovníky - 1. lekce

### ISSUE THREAD

**Issue by Marketa418** [Marketa418/czechitasUkolCviceni_1.py#1]
Ahoj Jiří @pesikj, 

mám hotové všechny úkoly. Snad dobře :D. Ale u 4. úkolu nemám poslední bod - nešlo mi vymyslet, jak nahradit mezeru lomítkem. 

Děkuji za opravu a přeji hezký den.

**Comment by pesikj** [comment]
Ahoj :-)

### 1. úkol :heavy_check_mark:

V podmínce nemusí být porovnání s `True`, protože ta hodnota ve slovníku je `True` sama o sobě, stačí tedy takto:
​
```python
  if baliky[kodBaliku]:
    print ("Balík je na cestě.")
```
​
### 2. úkol :x:
​
Ve druhém úkolu bys měla vyřadit součástku ze slovníku. Ty ji přiřazuješ hodnotu 0, ale součástka stále zůstává ve slovníku. Je to stejný případ, jako jsme řešili na hodině s opékáním buřtů - nejprve jsme jedné osobě přiřadili 0 a pak ji odebrali ze slovníku pomocí funkce `pop()`. Použij tedy prosím ve svém programu funkci `pop()`.
​
### 3. úkol :heavy_check_mark:
​
Super :-)
​
### 4. úkol :heavy_check_mark:

Ta podmínka pro lomítko by mohla vypadat např. takto, jinak je úkol správně. Super je, že vkládáš mezeru i mezi písmena, to nebylo v zadání a je to tak lepší :-)​

```python
  if pismeno == " ":
    print("/", end=" ")
```
​
### 5. úkol :heavy_check_mark:
​
Taky super :-)
​
Shrnuti + pozadavky na upravu
​
Skvělé. Oprav si prosím příklad 2, aby sis vyzkoušela použití funkce `pop()`, je to v materiálech na cvičení. Zatím ti píšu 4 body, ale ten poslední získáš snadno :-)

**Comment by pesikj** [comment]
@Marketa418 Můžeš mi prosím ještě napsat svoje příjmení? Nemůžu tě dohledat v tabulce s uživatelskými jmény. Můžeš klidně mailem, pokud to nechceš psát do komentáře, moc děkuji :-)
