### ISSUE TITLE
ukoly z lekce 5

### ISSUE THREAD

**Issue by Marketa418** [Marketa418/czechitasUkolCviceni_1.py#5]
Ahoj Jirko @pesikj :), 

dala jsem na git úkoly z lekce 5. Doufám, že budou všechny dobře :). Tyto úkoly byly bezva, protože v materiálech (kodim, cvičení na breakroomu, přednáška s Tebou) se dal najít postup, jak příklad vyřešit :).  

Děkuji a přeji hezký víkend :).
Markéta

**Comment by pesikj** [comment]
Ahoj Markéto,

### Příklad 21

Super, jen pro poslední řádek by bylo obecnější použít -1 jako parametr pro `iloc` :-) A chválím i za pokročilé příklady :-)

### Příklad 22

Super :-)

### Příklad 23

Taky správně, jen není úplně časté používat jako index hodnoty, které jsou v tabulce na více řádcích. Pro výběry podle států můžeš použít též dotazy. Ale pandas to podporuje, řešení je určitě v pořádku :-)

### Příklad 24

Super :-)

### Příklad 25

Tady chválím za pokročilou variantu. Opět tady platí poznámka s neunikátním indexem, např. ta dvě města bys mohla vyfiltrovat taky pomocí funkci `isin`, kterou jsme používali. Ale Pandas ty duplicitní indexy povolují, takže s jejich používání není problém, pouze je potřeba opatrnost :-) (třeba při propojení tabulek, uvidíš na příští lekci).

### Shrnutí

Vše máš správně, připisuji 5 bodů :-) Jsem moc rád, že jsi vše našla v materiálech ke kurzu, tak by to ideálně mělo být vždy :-)
