### ISSUE TITLE
Úkoly z lekce 6

### ISSUE THREAD

**Issue by Marketa418** [Marketa418/czechitasUkolCviceni_1.py#6]
Ahoj Jirko :) @pesikj,

úkoly z lekce 6 jsou splněny. Snad dobře :). 

Děkuji a hezký start do nového týdne.
Markéta

**Comment by pesikj** [comment]
Ahoj Markéto,

promiň, že mi to tak trvalo :-(

### Příklad 26

Super :-)

### Příklad 27

Taky super :-)

### Příklad 28

Taky super :-)

### Příklad 29

Taky super :-)

### Příklad 30

Taky super :-)

### Shrnutí

Všechny příklady byly správně a ve většině příkladů bylo zpracováno i bonusové zadání, takže připisuji 5 bodů :-)

**Comment by Marketa418** [comment]
Jirko, děkuji moc za opravu :).
