### ISSUE TITLE
Úkoly z lekce 7

### ISSUE THREAD

**Issue by Marketa418** [Marketa418/czechitasUkolCviceni_1.py#7]
Ahoj Jiří @pesikj  :), 

poslala jsem splněné úkoly k lekci 7. Ještě prosím o kontrolu lekce 6. 

Doufám, že jsou úkoly v pořádku :). Jen v té vizualizaci nějak nechápu, proč ty data musím dávat do data Series. V úkolu ty data mám v dataFrame (asi? :)) a ten graf jde.

Děkuji a přeji hezký den, 
Markéta

**Comment by pesikj** [comment]
Ahoj Markéto,

### Příklad 31

Super, akorát u prvních pěti je 0 v zápisu zbytečná :-)

```python
print(temperature_without_99_serazene.iloc[:5])
```

### Příklad 32

Taky super :-)

### Příklad 33

Taky super :-)

### Příklad 34

Super, líbí se mi, že jsi `title` vložila přímo do funkce `bar()`.

### Příklad 35

Taky super :-)

### Shrnutí

Ohledně těch sérií - není to nutné dávat do sérií, grafy umí pracovat i s tabulkami. Pouze u tabulek se může stát, že těch sloupců je tam moc a `matplotlib` je z toho zmatený, v tom je série bezpečnější. V příkladech na lekci jsme sérii používali, ale tvoje řešení s tabulkami je taky super, dobrá práce :-)

**Comment by Marketa418** [comment]
Jirko, moc díky za opravu :)
