### ISSUE TITLE
není úkol, prosba o radu

### ISSUE THREAD

**Issue by Marketa418** [Marketa418/czechitasUkolCviceni_1.py#8]
Ahoj @pesikj Jirko :), 

prosím dala jsem na git soubor mpsv.py. Jsou tam právě stažená data z MPSV v Json, ale nejde s tím vůbec pracovat, protože v souboru je jen 1 sloupec s názvem polozky, a v tom je několik tisíc řádku, které obsahují všechny informace. Ale ty řádky by se měli dělit na sloupce, např. podle ID, portalId....ty jednotlivé atributy jsou zde: https://data.mpsv.cz/web/data/volna-mista-za-celou-cr. Neměl by si prosím radu, jak ty informace z řádku rozdělit podle jednotlivých atribut do sloupců? 

Napadlo mě, celý ten json dát hned do csv, pak do Excelu, tam to upravit a pak s tím až pracovat v pythonu. Jenže je to zbytečná práce a pak si to zrovna můžu celé dělat v Excelu...

Děkuji a hezkou neděli, 
Markéta

**Comment by pesikj** [comment]
Ahoj Markéto,

ono je to dané strukturou toho JSONu, která není úplně ideální. Samotný seznam pracovních míst je tam ukrytý pod klíčem `polozky`. Jde to vyřešit třeba tím, že použiješ k otevření souboru modul `json` a pak můžeš s daty pracovat jako se slovníkem. Tím pádem můžeš do `pandas` načíst až to, co je pod klíčem `polozky`.

```python
import wget
import pandas
import json
#wget.download("https://data.mpsv.cz/od/soubory/volna-mista/volna-mista.json")

with open('volna-mista.json', encoding="utf-8") as json_file:
    data = json.load(json_file)
    data = data["polozky"]
    volna_mista = pandas.DataFrame(data)
    print(volna_mista.shape)
    volna_mista_chtena = volna_mista[volna_mista["cizinecMimoEu"] == True]
    print(volna_mista_chtena.shape)
```
